<$PLAN9/src/mkhdr

LIB=libevt.a
LDFLAGS="-lrt -lm -lc -L/usr/lib /usr/local/lib/libelectron.a"
CFLAGS=-Os -I/usr/include -I/usr/local/include/electron

OFILES=\
       input.$O\
       draw.$O\
       evt.$O\


HFILES=\
      evt.h\


<$PLAN9/src/mklib
