<$PLAN9/src/mkhdr

LIB=libneutron.a

LDFLAGS="-lrt -lm -lc -L/usr/lib"
CFLAGS=-Os -I/usr/include -I/usr/local/include/electron -I../include

OFILES=\
       input.$O\
       draw.$O\
       evt.$O\
       edraw.$O\


HFILES=\
      evt.h\
      edraw.h\


<$PLAN9/src/mklib
