<$PLAN9/src/mkhdr
# chicanery is the version of electron that uses plan9port
TARG=chicanery
BIN=/usr/local/bin/
LDFLAGS="-lrt -lm -lc -L/usr/lib ../../libneutron/libneutron.a /usr/local/lib/libelectron.a"
CFLAGS=-Os -I/usr/include -I/usr/local/include/electron -I../../include

OFILES=chicanery.$O\
       userfunctions.$O\

<$PLAN9/src/mkone
