<$PLAN9/src/mkhdr
# chicanery is the version of electron that uses plan9port
TARG=chicanery
BIN=/usr/local/bin/
LDFLAGS="-lrt -lm -lc -L/usr/lib"
CFLAGS=-Os -I/usr/include -I/usr/local/include/electron
LIB=/usr/local/lib/libelectron.a ../../libedraw/libedraw.a ../../libevt/libevt.a

OFILES=\
       chicanery.$O\
       userfunctions.$O\

<$PLAN9/src/mkone
