<$PLAN9/src/mkhdr
BIN=$ELECTRON_PLATFORM_ROOT/sys/bin
LDFLAGS="-lrt -lm -lc -L/usr/lib /usr/local/lib/libelectron.a" 
CFLAGS=-Os -I$ELECTRON_PLATFORM_ROOT/sys/include -I/usr/include -I/usr/local/include/electron
DIRS = libevt\
       libedraw\
       cmd/chicanery\

<$PLAN9/src/mkdirs
