<$PLAN9/src/mkhdr
BIN=/usr/local/bin
LDFLAGS="-lrt -lm -lc -L/usr/lib"  
CFLAGS=-Os -I$ELECTRON_PLATFORM_ROOT/sys/include -I/usr/include -I/usr/local/include/electron
DIRS = libneutron

<$PLAN9/src/mkdirs
